# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jdiaz <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/10 16:01:51 by jdiaz             #+#    #+#              #
#    Updated: 2018/11/14 17:06:43 by jdiaz            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CFLAGS = -Wall -Wextra -Werror

SRC =  ft_memccpy.c \
	   ft_putnbr.c \
   	   ft_strequ.c \
   	   ft_strnequ.c \
	   ft_memchr.c \
   	   ft_putnbr_fd.c \
	   ft_striter.c \
	   ft_strnew.c \
	   ft_atoi.c \
 	   ft_memcmp.c \
   	   ft_putstr.c \
   	   ft_striteri.c \
	   ft_strnstr.c \
	   ft_bzero.c \
   	   ft_memcpy.c \
   	   ft_putstr_fd.c \
	   ft_strjoin.c \
	   ft_strrchr.c \
	   ft_isalnum.c \
	   ft_memdel.c \
   	   ft_strcat.c \
   	   ft_strlcat.c \
	   ft_strsplit.c \
	   ft_isalpha.c \
	   ft_memmove.c \
	   ft_strchr.c \
   	   ft_strlen.c \
	   ft_strstr.c \
	   ft_isascii.c \
	   ft_memset.c \
   	   ft_strclr.c \
	   ft_strmap.c \
   	   ft_strsub.c \
	   ft_isdigit.c \
	   ft_putchar.c \
	   ft_strcmp.c \
   	   ft_strmapi.c \
	   ft_strtrim.c \
	   ft_isprint.c \
   	   ft_putchar_fd.c \
	   ft_strcpy.c \
   	   ft_strncat.c \
	   ft_tolower.c \
	   ft_itoa.c \
 	   ft_putendl.c \
	   ft_strdel.c \
   	   ft_strncmp.c \
	   ft_toupper.c \
	   ft_memalloc.c \
	   ft_putendl_fd.c \
	   ft_strdup.c \
   	   ft_strncpy.c \
	   ft_lstnew.c \
	   ft_lstdelone.c \
	   ft_lstdel.c \
	   ft_lstadd.c \
	   ft_lstiter.c \
	   ft_lstmap.c \
	   ft_lstaddtail.c \
	   itoa_base.c \
	   ft_sort_list.c \
	   ft_num_words.c \
	   get_next_line.c \
	   b_printf.c \
	   utls.c \
	   printers.c \
	   num_printers.c \
	   func_dispatcher.c \
	   decimals.c

OBJ=$(SRC:.c=.o)

all: $(NAME)

$(NAME):
	@gcc $(CFLAGS) -c $(SRC)
	@ar rc $(NAME) $(OBJ)
	@ranlib $(NAME)
	@echo "\033[32mBuilt library.\033[0m"

clean:
	@/bin/rm -f $(OBJ)
	@echo "\033[32mCleaned up libft object files.\033[0m"

fclean: clean
	@/bin/rm -f $(NAME)
	@echo "\033[32mCleaned up libft.a\033[0m"

re: fclean all

.PHONY: all clean fclean re
